### ISSUE TITLE
Python 3.3 - AttributeError: 'OscMessageBuilder' object has no attribute 'dgram'

### ISSUE THREAD

**Issue by arshiacont** [attwad/python-osc#27]
First of all, great thanks for this extremely useful lib! It works totally fine on Python 3.4.

For some strange reasons, I need to get it working on Python 3.3

I downloaded the 1.4.2 (which states Python 3.3+). Everything is fine but when I initiate a send message I get  the "AttributeError: 'OscMessageBuilder' object has no attribute 'dgram'" error.

Any hints on how to overcome this on Python 3.3?

**Comment by arshiacont** [comment]
Update: This was totally my fault! Was forgetting the message build stage! I confirm that 1.4.2 works fine on Py 3.3+

**Comment by attwad** [comment]
Ok then glad you found the issue :)
